name: auxivie
description: Plateforme de mise en relation entre professionnels de l'aide à domicile et familles
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # State management
  provider: ^6.1.1
  
  # Base de données locale
  sqflite: ^2.3.0
  path: ^1.8.3
  
  # API & Réseau
  http: ^1.2.0
  
  # UI & Utilitaires
  intl: ^0.18.1
  table_calendar: ^3.0.9
  image_picker: ^1.0.4
  
  cupertino_icons: ^1.0.6

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  # Assets
  assets:
    - assets/images/
    - assets/colors.json

  # ⚡ Désactiver LLDB pour iPhone réel
  config:
    enable-lldb-debugging: false

